export type ProductCategoryKeyType =
    | "men"
    | "women"
    | "new"
    | "sport"
    | "kids"
    | "sale"
    | "sneakers"
    | "boots"
    | "sandals"
    | "formal"
    | "casual"
    | "accessories"
    | "running"
    | "walking"
    | "work"
    | "outdoor"
    | "luxury";

export type ProductCategoryLabelType =
    | "Men"
    | "Women"
    | "New"
    | "Sport"
    | "Kids"
    | "Sale"
    | "Sneakers"
    | "Boots"
    | "Sandals"
    | "Formal"
    | "Casual"
    | "Accessories"
    | "Running"
    | "Walking"
    | "Work"
    | "Outdoor"
    | "Luxury";
